import type { Metadata } from "next";
import "./globals.css";
import { sfProDisplay } from "./ui/fonts";

export const metadata: Metadata = {
  title: "Live Chat",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${sfProDisplay.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
